name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.13.4'

      - name: Install fuse
        run: sudo apt-get update -qy && sudo apt-get install -qy fuse

      - name: Build and test
        run: make
