name: Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Install fuse
        run: sudo apt-get update -qy && sudo apt-get install -qy fuse

      - name: Configure GOPATH
        run: echo "GOPATH=$(go env GOPATH)" >> "$GITHUB_ENV"

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
