name: Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Install fuse
        run: sudo apt-get update -qy && sudo apt-get install -qy fuse

      - name: Configure GOPATH
        run: echo "GOPATH=$(go env GOPATH)" >> "$GITHUB_ENV"

      - name: Build release artifacts
        run: make dist

      - name: Package release artifacts
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy python3 python3-pip
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install --upgrade packagecore setuptools
          packagecore -o dist/ "${GITHUB_REF_NAME}"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
